name: Sync fork

on:
    schedule:
        - cron: '*/30 * * * *' # Every 30 minutes
    workflow_dispatch:

jobs:
    sync:
        runs-on: ubuntu-latest
        if: ${{ github.repository != 'nexpid/CloudSync' }}

        steps:
          - uses: tgymnich/fork-sync@v2
            with:
                head: main
                base: main
                merge_method: rebase
                retries: 2